# Generated by Django 4.0.4 on 2022-05-31 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projecs',
            new_name='Projects',
        ),
    ]
