# Generated by Django 4.0.4 on 2022-06-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_projecs_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.FilePathField(path='/projects/img'),
        ),
    ]
